repos:
  - repo: local
    hooks:
      - id: pre-commit-tests
        name: Pre-commit tests
        entry: bash -c 'pytest $(cat .implemented-test-files)'
        language: system
        pass_filenames: false